name: Test and Build

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        env:
          cache-name: lr-chl-cat-grdl-cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-grdl-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-grdl-${{ hashFiles('**/build.gradle') }}

      - name: Gradle Build
        run: gradle clean build
